version: "3"
services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui
    ports:
      - 9096:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - /ht/docker/kafka-ui/config.yml:/etc/kafkaui/dynamic_config.yaml