# Use postgres/example user/password credentials
services:
  db:
    image: postgres:16.3
    restart: always
    ports:
      - "5432:5432"
    # set shared memory limit when using docker-compose
    shm_size: 256mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
     - type: bind
       source: /tmp/postgres/data
       target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data/pgdata
      NODE_ENV: production
volumes:
  db_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /tmp/postgres/data
      o: bind